FORMAT: 1A

# Products

Products is a simple API allowing users to manage the storing and inventory of products.

# Group Products

## Products Collection [/products]

### Get Individual Product [GET/products/{parameter}]
+ Parameters
    + parameter: (string,required) - The id or name of the product

    You can search writing either the name or the id of the product

+ Response 200 (application/json)
    + Attributes
        - include Product

+ Response 400 (application/json)
    + Attributes (Error)


### Get Products Sort by Name or Popularity [GET/products{?sort,limit,page}]
+ Parameters
    + sort: (enum[string]) - The way the products are goint to be sort when showing
        + Default: `name`

        + Members
            + `name`
            + `popularity`
            + `-name`
            + `-popularity`
        
    + limit: (number,optional) - Maximum number of products per page
        + Default: `5`
    + page: (number,optional) - Page to show
        + Default: `1`

+ Response 200 (application/json)
    + Attributes
        - products(array[Product])

+ Response 400 (application/json)
    + Attributes (Error)


## Products actions [/products]


### Add a Product [POST/products]
+ Headers
    Content-Type: application/json
    Authorization: JWT

+ Request
    + Attributes (Create)

+ Response 200 (application/json)
    + Attributes
        - include Product

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)


### Delete a Product [DELETE/products/{id}]
+ Headers
    Content-Type: application/json
    Authorization: JWT

+ Parameters
    + id: `1` (number,required) - The id of the product

+ Response 204 (application/json)
    + Attributes (Error)

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


### Like a Product [POST/products/{id}/like]
+ Headers
    Content-Type: application/json
    Authorization: JWT

+ Parameters
    + id: `1` (number,required) - The id of the product

+ Request
    + Attributes
        - userId: `1` (number, required) - The id of the user logged

+ Response 200 (application/json)
    + Attributes
        - include Product

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


### Buy a Product [POST/products/{id}/buy]
+ Headers
    Content-Type: application/json
    Authorization: JWT
    
+ Parameters
    + id: `1` (number,required) - The id of the product

+ Request
    + Attributes
        - quantity: `1` (number, required)

+ Response 200 (application/json)
    + Attributes
        - include Log

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


### Update a Product Price [PATCH/products/{id}]
+ Headers
    Content-Type: application/json
    Authorization: JWT

+ Parameters 
    + id: `1` (number,required) - The id of the product

+ Request
    + Attributes
        - Price: `1` (number, required)

+ Response 200 (application/json)
    + Attributes
        - include Product

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


# Users 

## user actions [/users]

### Add users [POST/users]

+ Request
    + Attributes
        - name: `userName` (string, required)
        - password: `123` (string, required)

+ Response 200 (application/json)
    + Attributes
        - include User

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


### update users [GET/users/{id}/admin]
+ Headers
    Content-Type: application/json
    Authorization: JWT

+ Parameters 
    + id: `1` (number,required) - The id of the user

+ Response 200 (application/json)
    + Attributes
        - include User

+ Response 400 (application/json)
    + Attributes (Error)

+ Response 401 (application/json)
    + Attributes (Error)

+ Response 403 (application/json)
    + Attributes (Error)

+ Response 404 (application/json)
    + Attributes (Error)


# Data structure

## Product (object)
- id: `1` (number) - The ID of the Product
- name: `My product name` (string) - The name of the product
- stock: `1` (number) - The stock of the product
- price: `1` (number) - How much you will pay for the product
- likes: `1` (number) - How many people have liked the product


## Error (object)
+ code: 400 (number) - Status code
+ message (string) - Status message
+ description (string) - Status description


## Create (object)
- name: `My product name` (string) - The name of the product
- stock: `1` (number) - The stock of the product
- price: `1` (number) - How much you will pay for the product


## Log (object)
- id: `1` (number) - The ID of the logge
- productId: `1` (number) - The ID of the product bought
- userId: `1` (number) - The ID of the user that purchased the product
- quantity: `1` (number) - The quantity purchase
- total: `1` (number) - The total of the purchase
- logDate: `01-01-2018` (string) - the date of the purchase

## User (object)
- id: `1` (number) - The ID of the user
- name: `1` (string) - The name of the user
- password: `1` (string) - The password of the user
- isAdmin: `1` (number) - Wether the user is admin (1) or not (0)



